manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: sayu-hub  # pmw3610-driver のフォーク
      url-base: https://github.com/sayu-hub
    - name: Dist16384   # あなたのフォーク
      url-base: https://github.com/Dist16384
    - name: caksoylar  # <-- RGB LED
      url-base: https://github.com/caksoylar  
    - name: pointing-acceleration
      url-base: https://github.com/rain-bbb
    - name: yamaryu211
      url-base: https://github.com/yamaryu211
    - name: mjmjm0101
      url-base: https://github.com/mjmjm0101

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      path: zmk
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: Dist16384
      revision: main
      path: modules/zmk-pmw3610-driver
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: v0.3
    - name: zmk-pointing-acceleration
      remote: pointing-acceleration
      revision: main
    - name: zmk-input-processor-temp-layer-threshold
      remote: yamaryu211
      revision: main
    - name: zmk-input-processor-scroll-inertia
      remote: mjmjm0101
      revision: fix/coasting-weak-input-freeze

  self:
    path: config
